AWSTemplateFormatVersion: '2010-09-09'

Resources:

  UploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: 'Private'
      VersioningConfiguration:
        Status: 'Enabled'

Outputs:
  UploadBucket:
    Value: !Ref UploadBucket
