AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  LambdaFunctionArn:
    Type: String

Resources:

  UploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: 'Private'
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Function: !Ref LambdaFunctionArn
            Event: 's3:ObjectCreated:*'

Outputs:

  UploadBucket:
    Value: !Ref UploadBucket
